# config file containing credentials for RDS MYSQL instance , S3

# example with HANK's code
rds:
  bobsim_schema:
    username: "admin"
    password: "bobsim2020"
    url: "production-bobsim-aurora.cluster-cm9kakdihdlv.ap-northeast-2.rds.amazonaws.com"

  public_data:
    username: "admin"
    password: "bobsim2020"
    url: "production-bobsim-aurora.cluster-cm9kakdihdlv.ap-northeast-2.rds.amazonaws.com"


s3:
  url: "https://production-bobsim.s3.ap-northeast-2.amazonaws.com"
